# Generated by Django 4.2.7 on 2025-07-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Caption for the image (max 100 characters)', max_length=100)),
                ('image_url', models.URLField(help_text='URL to the image stored in CDN', validators=[posts.models.validate_image_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='posts_post_user_id_1547df_idx'), models.Index(fields=['created_at'], name='posts_post_created_dadbfe_idx'), models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'), models.Index(fields=['user', '-created_at'], name='posts_post_user_id_b93466_idx')],
            },
        ),
    ]
